### ISSUE TITLE
What does a perfect day look like to you?

### ISSUE THREAD

**Issue by sindresorhus** [HugoGiraudel/ama#11]

**Comment by HugoGiraudel** [comment]
This is a tough one, so I will go with *my bed*.

I just run a simulation and I evaluated the time spent sleeping for my whole like to be around **36%**. I hardly think there is any other place I've ever spent so much time in. Also, I like to think that if I go to bed every night, it's because I like it.

*PS: if you're interested by the computation, please ask. :)*

**Comment by HugoGiraudel** [comment]
Is there even such a thing as a perfect day? I have been thinking about this since I saw your question and I must say I can't really figure out a way to answer it. Instead, I will tell about what a good day would be. I feel like it is more realistic and is actually more helpful to figure out what's important than to imagine what would be the day of my life.

I would start with saying that I am lucky bastard as I live a lot of good days at this time of my life. 

It starts with waking up in a nice flat, comfy bed, ideally with the cats purring next to me (unfortunately they don't do that a lot). Then I get to work. My favourite weather is a soft sun with a lot of wind. A perfect day would definitely be sunny and windy.

My full time job gives me the opportunity to work on interesting projects with great people from very different backgrounds. My work is my passion. My passion is my work. I can contribute, learn and get paid all at the same time. This is an amazing feeling.

I used to work in the banking industry, where everybody had their desk, sat there and did not make much sound. Business was serious. Unfortunately this is not the way I enjoy working. I am not much a desk kind of guy so it is important for me to be allowed to work the way I want. I usually spend the day working on the couch for instance. When I am getting stuck on something, I like to have a coffee break and browse Twitter for a moment to get my mind off. It helps me getting started again.

After a day of work, a good day would be joining my girlfriend for a drink at this truly nice cocktail bar near our place. Then probably a burger somewhere; you can't go wrong with a burger. I am not a big fan of partying, so I think after that I'd rather be at home and maybe watch a movie or something.

I would probably end my day with a bit of open-source work if I feel like it, or just browsing Twitter and GitHub. Then, go to bed and start over.

I don't know if this is a perfect day, but this would be a good day for sure. And I am lucky to live this on a regular basis. :)
