### ISSUE TITLE
What's your favorite place on earth and why?

### ISSUE THREAD

**Issue by sindresorhus** [HugoGiraudel/ama#12]

**Comment by HugoGiraudel** [comment]
This is a tough one, so I will go with *my bed*.

I just run a simulation and I evaluated the time spent sleeping for my whole like to be around **36%**. I hardly think there is any other place I've ever spent so much time in. Also, I like to think that if I go to bed every night, it's because I like it.

*PS: if you're interested by the computation, please ask. :)*

**Comment by HugoGiraudel** [comment]
Here is how I came up with 36%. A few days ago I was browsing 9gag and found [an interesting infographics](https://s-media-cache-ak0.pinimg.com/736x/f8/11/5d/f8115d45b29b608b9086627804f71587.jpg) about the recommended sleeping time per age group, according to the National Sleep Foundation (didn't even know such a thing existed).

So I started laying down the numbers to figure out how many hours I have spent sleeping in my whole life, taking into account that between 17 and 19 I slept *very little*. After a few minutes, I came up with this **36%**, which is probably wrong by one or two percent in one way or the other.

I've been curious about this so I coded a little JavaScript function to compute the average amount of time spent sleeping in a lifetime based on age. Just in case, here it is: http://jsfiddle.net/24r6Leet/. :)
