### ISSUE TITLE
Do you believe in God?

### ISSUE THREAD

**Issue by mattdrose** [HugoGiraudel/ama#14]
How did you get to that belief?

I like the AMA idea. Figured I'd go for a hot topic ;)

Thanks!

**Comment by HugoGiraudel** [comment]
I don't, yet I am part of —like most French people I suppose— a somehow Christian family. People got married in a church, the generation of my parents and grand-parents use to go frequently to the Mass, and so on.

Between 7 and 13, my parents made me take “religious classes” (roughly 1 hour a week). Their idea was not to enforce any religious belief of any kind, but to raise me with an open mind regarding religion. And the point of these classes was really all about this: teaching kids about the christian religion, what it is, what it is not, what do people believe in, why... 

When I was a kid, it kind of annoyed me to go to these classes because I had no idea wether I should believe in God or not. I did not feel quite like it and at the same time I felt quite a shame not to believe. At the same time, no one in my family never really admitted that they believed or not, so it has always been a very intimate topic I suppose. 

Now looking back at all this, I am glad to have had those classes because I can have my own opinion about this. Which is as simple as I do not believe in God. :)

**Comment by mattdrose** [comment]
Thanks for you transparency man! I think it's pretty cool that you have such an appreciative perspective on something that probably annoys many. Cheers
