### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by enociz** [HugoGiraudel/ama#17]
What does your workflow look like when you work on the front-end side of things? 

I read that you don't build full pages for work but instead make components/modules on #9 . How do you plan, prototype and publish these? 

Do you use a different workflow on non-work things?

Sorry if that's just a soup of questions.

**Comment by HugoGiraudel** [comment]
> What does your workflow look like when you work on the front-end side of things? I read that you don't build full pages for work but instead make components/modules on #9. How do you plan, prototype and publish these?

I think non-technical workflow is more related to the company or the project than the individuals taking part in the project. Therefore, I am not quite sure how to answer your question so I will tell you about our typical workflow at Edenspiekermann in Berlin.

A team usually consists of a product owner (which is not necessarily the client, we sometimes have a product owner inside our own team to ease the workflow with the client), a scrum-master, one or two designers and one or two developers. The mileage may vary depending on the project.

Edenspiekermann is heavily relying on scrum and agile methodologies for the daily workflow, hence the presence of a scrum-master in every team. We iterate on a project in a given amount of 2-weeks sprints, each sprint setting up goals and having its own set of stories (things to do). Then, we usually take one hour at the beginning of a sprint to discuss the stories and create tasks for each of them. We use ScrumDo to keep track of all of this, and usually have a physical board as well because some people just prefer that way.

After that, everybody works pretty much on what they want. We don't assign stories directly. We tackle what we feel like doing; we just make sure that other people know what we do so that we don't end up doing twice the same work. Depending on the project, the features and more importantly the developers, we try to do a lot of pair programming. Some developers like it, some developers don't. I personally really enjoy it.

We use Git as a version controler and host all our projects on private GitHub repositories. Although we usually don't use the issue tracker, or very little. As I said, we use ScrumDo and physical agile boards to keep track of everything, so we only create GitHub issues for technical things that need to be improved or refactored. We work with branches in a Git flow fashion, and submit pull-requests before merging any feature in the main branch. This allows us to do some code review; two sets of eyes are always better than one.

Regarding the design side of things, we try to avoid the battle between designers and developers. As much as possible, we sit together and try things directly in the browsers, rather than having the not-so-great “mock-up > building” workflow. 

Several times in a sprint, we try to push the current state of work on a staging environment so that we can try it in different situations (such as handheld devices) and show it to relevant external actors (editorial team, stakeholders...). We usually rely on Heroku for that; it is a quick and efficient solution.

> Do you use a different workflow on non-work things?

I will assume by *non-work*, you mean outside of my full-time job at Edenspiekermann, so basically open-source contributions and side projects.

In that case, I go much easier. Well, GitHub is basically my workflow. I host everything on GitHub, heavily use the issue tracker as well as pull-requests. I like to review my own code through pull-requests as it helps me catching things I didn't see in the editor or the git diff.

I must say that is pretty much it. I also have my own Trello board to help me keeping track of things as I work on so many projects. I also use it to manage my daily life, setting me reminder to do this or that. I should write an article about Trello, very helpful outside of work as well.

That's it. I hope it answers your question. :)

**Comment by enociz** [comment]
This answered pretty much what I was asking.

On a side note, would you in anyway know where Edenspiekermann came from / what it means? I do see that it is evidently German but does this have anything to do with the name?

**Comment by HugoGiraudel** [comment]
I believe the name comes from its founder: [Erik Spiekermann](https://twitter.com/espiekermann). :)
