### ISSUE TITLE
If you could change one thing about Sass with a click of your fingers, what would it be?

### ISSUE THREAD

**Issue by davetgreen** [HugoGiraudel/ama#20]

**Comment by HugoGiraudel** [comment]
I don't know. The thing is, I used to beg for a lot of features when I was getting started with Sass, such as a function to remove the unit of a length, a way to extend across different media contexts and other things more or less crazy. Now that I have what I dare calling a good knowledge of the language, I don't need them anymore. More than that: I understand why we don't have them and why we don't necessarily need them. 

Because of this, I am not sure what I would like to add to the language. I feel like @nex3 and @chriseppstein are doing one hell of a job to keep the language both powerful, robust and friendly. It is a colossal task, especially when you involve forward and backward compatibility with CSS. Trust me, it's hell. Those folks are saints.

I think one feature that I could enjoy, although I feel like it could be severely abused and over-used, is a way to iterate on the content passed through the `@content` directive. It would allow us to do some interesting things, even if I am not quite sure it would be that a killer feature. But I could find a way to exploit it for fun, for sure. :)
