### ISSUE TITLE
What do you think about using inline styles with react ?

### ISSUE THREAD

**Issue by romariclaurent** [HugoGiraudel/ama#22]
http://m.youtube.com/watch?v=ERB1TJBn32c

**Comment by HugoGiraudel** [comment]
If I still haven't replied to this question yet, it is because I don't know to answer it. 

I have read a bit about inline styles with React, but I never really tried it. I can see the benefit of this approach, especially regarding style scoping but I would have a hard time telling how I feel about it without actually trying it.

Maybe I'll revisit this answer some day. :)
