### ISSUE TITLE
What's your opinion of Thoughtbot's Refills components?

### ISSUE THREAD

**Issue by maxx1128** [HugoGiraudel/ama#25]
Got an idea to make this separate :) So for Refills, any circumstances you feel they're best used or avoided?

**Comment by HugoGiraudel** [comment]
To be honest, I never really used Refills. I can only bet it is good because it is made by the kind folks at Thoughtbot.

I can only assume 2 things here. The first is that it's mostly a lightweight Bootstrap. It provides ready-to-use components as HTML/CSS/JS snippets that you can quickly paste and use in your projects. Therefore, it is probably very handy when prototyping or building a “design-less interface” such as a quick admin dashboard.

Secondly, I believe they (only) make sense as part of the Thoughtbot ecosystem. By this I mean that if you use Refills, you better use Bourbon and Neat as well. They are built by the same persons as another tool in the box, so it would be silly (to me) to use Refills outside of this box.

I hope it helps. :)
