### ISSUE TITLE
Eyeglass issue 

### ISSUE THREAD

**Issue by kapena** [HugoGiraudel/ama#29]
Hi Hugo,

I noticed that you wrote a real neat little [article](http://www.sitepoint.com/author/hgiraudel/) about eyeglass on sitepoint. Since you seem to know about it I thought you might have some insight on my issue that I am having with it atm. 

## Issue with eyeglass integration 
So wanted to use the Sassy Modular Scale project in my build by using eyeglass. Although I ran into a few issues with it and posted a STO post on it. Nobody really knew how to solve the problem and now I'm just stuck wondering how to get it to work properly. Here's my post on [STO](http://stackoverflow.com/questions/31507406/how-set-up-my-directory-to-work-with-eyeglass-on-fetching-modularscale) where I explain my issues with integrating eyeglass and modular scale.   

I'd really appreciate it if you set up a mock repo on github which explains how to integrate eyeglass with modular scales. That would help me very much. 

Thank you,

Brent W

**Comment by HugoGiraudel** [comment]
Hey Brent.

Did I write something about Eyeglass? Your link doesn't head to any article of mine. Because the truth is, I didn't really give it a serious try. I played with it a few times and didn't really succeed in making what I want, so I gave up. I should retry it at some point.

Sorry for not being able to help much. Maybe ask @chriseppstein directly on Twitter. :)
