### ISSUE TITLE
How do you get started on your side projects?

### ISSUE THREAD

**Issue by ankurkaushal** [HugoGiraudel/ama#40]
As someone who really wants to have some side projects, most of the time I am clueless as to where to start. Sometimes I feel I don't know enough about the language (in this case JS) to start with the project, sometimes I would struggle with design (I want my side project to look good) etc. How do you overcome that?

**Comment by HugoGiraudel** [comment]
Hey,

For starters, I recommend you read those 2 questions which might contain some things you could find interesting and relevant on the matter:

* [How does your overall process looks like when building a new side project?](https://github.com/HugoGiraudel/ama/issues/24)
* [What are your recommendations for getting more involved in Open Source projects?](https://github.com/HugoGiraudel/ama/issues/23)

Now, I'd say you have to get started in one way or another. Don't worry too much about your project not being perfect at first. You gotta start somewhere. Make it work, first and foremost. Once it work, refine things; review your code; polish your design. Improve the quality once it works, not before. This would premature optimisation, which is usually not very good as it can come in the way of productivity.

Then once you feel like you've done your best with your project, put it on GitHub and start working on everything that could come along side with the project: the documentation, the site, the yet-to-come features, and so on. 

At this point, you can start collecting feedback and asking for review. I would advice asking for specific things rather than a full blown review as people's time might be limited. For instance, ask a confident JavaScript developer to review the JS part. Ask a designer what he thinks about the design. You get the idea.

I like to get obsessive with some of my best side projects. For instance I have spent countless hours on [Sass Guidelines](http://sass-guidelin.es) (which is probably my biggest OSS project) optimising the styles, the documentation, and other tiny details that nobody gives a damn about. Doing this makes me proud of my work, and even more confident in showing it to others.
