### ISSUE TITLE
Do you actually write as much JavaScript code as css/sass?

### ISSUE THREAD

**Issue by Zhouzi** [HugoGiraudel/ama#50]
You're pretty well known for your Sass contributions but I was curious about your gut for JavaScript. Do you consider yourself a css/sass expert or a front-end "generalist"? How much js code do you actually write? And what are the js frameworks/tools you found yourself playing with lately?

**Comment by HugoGiraudel** [comment]
Hey, thanks for asking!

Most of my days are spent writing either Sass or JavaScript. All the projects I work on at Edenspiekermann are using React, so this is definitely something I’m getting used to. Although, I am not an amazing JavaScript developer, even if I do enjoy writing JavaScript. I’ve recently been reworking an old JS project of mine to port it over to ES6 and write test: https://github.com/HugoGiraudel/CRUD.js. 

That being said, I am better known for my Sass and CSS expertise, even in house at Edenspiekermann. I happen to write a lot of JavaScript because it’s actually most of our front-end (and middleware) tech stack, but my skill set still heavily goes around CSS.

**Comment by Zhouzi** [comment]
CRUD.js looks nice, I'll have a deeper look :)

And what's your opinion on the distinction between front-end developers focused on css vs js? Do you think that the required skills are going to split the profession into two types of front-end developers?

**Comment by HugoGiraudel** [comment]
It really depends on the team. 

At Edenspiekermann, we don’t make the distinction in job titles: we just say *Frontend Developer*. However, we have very diverse profiles. Some of our Frontend Developers are actually very skilled in frontend JS, or even Node (middleware). Some others, like myself for instance, are more specialised in CSS (and in my case Sass). We don’t make a distinction, but we are aware of those different skillsets, and use this knowledge to bring our projects to their final destination. :)

On the other hand, a small team would probably need more polyvalent profiles since it is not always possible to have several frontend developers on a same project. Then, having a jack-of-all-trades knowing their way in both CSS and JavaScript is likely the best option. But it’s hard to find one (even if we have a few of them)!
