### ISSUE TITLE
What's the best job offer you've turned down?

### ISSUE THREAD

**Issue by esr360** [HugoGiraudel/ama#51]
And why did you turn it down? Do you regret it?

**Comment by HugoGiraudel** [comment]
Unfortunately, I am not good (for lack of a better word?) enough to get overwhelmed with countless job offers, although I did receive a few over the last 3 years, including the one getting me to Edenspiekermann where I work today. 

I turned a few of them down, but mostly because they were not quite interesting for my taste. They were about working for tiny startups which is usually not really I am aiming for. Sometimes, let’s be honest, the salary and the advantages were simply not good enough.

It is actually hard to find a good job offer where the job, the company, the location, the team, the salary, the advantages and the rest are good enough to ditch one’s current position.
