### ISSUE TITLE
Items on circle CSS

### ISSUE THREAD

**Issue by pabloermida** [HugoGiraudel/ama#54]
Hi Hugo, 

I read your article: http://hugogiraudel.com/2013/04/02/items-on-circle/
It´s very usefull for me, congratulations for the solution. But, I have a question, I need to implement a gui with the same idea, but with many levels of this circles with images, like a orbit visualization. 
Do you think that is the best aproach to develop in that case? Thanks in advance.
Regards, Pablo

**Comment by HugoGiraudel** [comment]
Hey there,

If you product is more about data visualisation that user interface, I would perhaps recommend digging into canvas for that rather than DOM elements. If it’s really about making a GUI, like a dashboard, using this technique might be a solution yes. Although it will probably be a bit hard to maintain. Try to tackle the problem slowly, baby steps, in order to make it as simple as possible.

**Comment by pabloermida** [comment]
Thanks Hugo, i'll consider that.

Regards, Pablo

2015-12-01 16:58 GMT+00:00 Hugo Giraudel <notifications@github.com>:
