### ISSUE TITLE
How are you liking N26?

### ISSUE THREAD

**Issue by mxstbr** [HugoGiraudel/ama#76]
It's been a few weeks/months (?) since you joined N26, how has it been? What's your impressions like, what's the team like, what's the tech like?

**Comment by HugoGiraudel** [comment]
I joined on September 1st. It’s been mostly good since then. The company is pretty big, with almost 200 people and counting and I have to say that’s quite a lot to deal with for me. I’m not particularly good at socialising, especially in a work environment so I tend to spend time working in rest areas rather than actual open spaces. People seem okay with that, so that’s fine.

Everybody is lovely. They’re all super friendly and we work in small cross-disciplinary teams (Scrum or Scrumban usually). Everything is quite smooth and flexible, even though we are in the middle of refining all of our processes to make our job easier and us globally more productive. It’s hard and it’s a company-wide move but I’m positive it’s going to pay on the long run.

Work itself is very interesting. I’m obviously not allowed to tell much about the projects themselves but we are doing some cool stuff with isomorphic React, Redux, CSS Modules and the like. It’s pretty challenging and quite fun to work on. I hope I’ll be able to show and tell more in a couple of weeks when we release one of the projects I’m currently working on. :)

I’m actively fighting for accessibility across the board, from business decisions to design to implementation to QA. It’s going to be a long battle that I’m not entirely sure to win but ultimately that’s why I’m there. That’s what I find intersting in my job nowadays. Makind a product for everyone. Including minorities. Including disabled people. Including weird edge cases. Accessibility is the reason I’m still in the web industry.

Over than that, the office is absolutely lovely. Lot of room, lounge areas, coffee, food and drinks. An interior designer/architect is currently redesigning it entirely and boy does it look good. I hope I can post some pictures when it’s fully done. 

So far, so good I’d say. :)

**Comment by mxstbr** [comment]
Sounds super interesting! Thanks for the in-depth answer!

If you want to, I'd be interested to hear more about 

> we are in the middle of refining all of our processes to make our job easier and us globally more productive

In what way? What wasn't working and what are you changing to make it work?

**Comment by HugoGiraudel** [comment]
I’ll be entirely honest and admit I’m not the best person to reply to this. Maybe we should have a AMA at N26, haha. I’ll suggest that. :)
