### ISSUE TITLE
Is the new Atom text editor is mature enought to compete with Sublime Text? Do you plan to use it?

### ISSUE THREAD

**Issue by labo-css** [HugoGiraudel/ama#8]

**Comment by HugoGiraudel** [comment]
To be perfectly honest, I only tried Atom once, when it was in closed beta. I managed to have an invite back then, and gave it a try. Although at this point, it was not stable enough.

I think it has gone through a lot since then and I am pretty sure it is mature enough to compete with other popular editors such as Sublime Text. Atom is *hackable* in a way that it can be easily extended in the same fashion as Sublime Text, so a lot of popular plugins from ST has been ported other to Atom.

Now as far as I'm concerned, I finally found a good workflow with Sublime Text so I don't plan on ditching it soon but at some point I might be switching. Although I must say that if I ever came to switch editors, I'd like to be for Vim. :)
