### ISSUE TITLE
Have you seen this project?

### ISSUE THREAD

**Issue by bjankord** [HugoGiraudel/ama#83]
Hey Hugo, I really enjoy all the work you've shared in the front-end dev community. I was curious if you've ever seen this project: https://github.com/bjankord/stylelint-config-sass-guidelines

Curious what your thoughts are on it.

**Comment by HugoGiraudel** [comment]
Hey there,

I didn’t know about this project, but I dig it! I like that you documented it very well and everything, that is super nice!

I’ll be honest, the management of this configuration on Sass Guidelines has always been a pain for me since it‘s unsynchronized with any scss-lint updates. I regularly miss new updates, rules and such. Maybe there is something to be done about it but that’s another story. :)

Congratulations on the project anyway, we should definitely link to it in Sass Guidelines. I created an issue about it on the main repo to remember it: https://github.com/HugoGiraudel/sass-guidelines/issues/419.
