### ISSUE TITLE
Do you prefer to write your own CSS for some projects or to use a framework like bootstrap?

### ISSUE THREAD

**Issue by shadeed** [HugoGiraudel/ama#9]

**Comment by HugoGiraudel** [comment]
Disclaimer: I do not like CSS frameworks. I tend to think they usually bring more overhead than help in a project. At work, we never start from a CSS framework. At best, we involve a third-party grid system but it's rather unlikely.

Now it should be pointed that I don't actually build sites. I work as a front-end developer on large projects, where I mostly build components rather than full-blown interfaces and most of my open-source work is about building API and services rather than websites. 

In the end, the few websites I have built on my own (http://hugogiraudel.com, http://sassdoc.com, http://sass-compatibility.github.io, http://whyalix.com) are so simple that it would have been a shame to use a framework.
