### ISSUE TITLE
Color for SASS variables in Sublime Text 3?

### ISSUE THREAD

**Issue by touhid-rahman** [HugoGiraudel/ama#90]
#Which color pallet package I can use to display color in my SASS variables in Sublime Text 3?

```
$black: #000
h1
    color: $black
```

As you can see, my current package (ColorHelper) is not showing color for SASS variables. 
[https://i.stack.imgur.com/cT5ai.jpg](https://i.stack.imgur.com/cT5ai.jpg)

**Comment by HugoGiraudel** [comment]
Hello.

I’m not sure this is possible because Sublime Text is a text editor, not an IDE. This means I’m not sure it keeps track of variable definitions within a file for instance, and thus cannot retrieve the color mapped to a variable.

I could be wrong of course, but as far as I can tell, there is no way to do this in Sublime Text.
